def DrawImage():
    print("\n"," "*15," BOOTH'S MULTIPLICATION ALGORITHM\n")
    print(" "*15,"           _________      ")
    print(" "*15,"          /         \ ")
    print(" "*15,"         |   Start   |   ")
    print(" "*15,"          \_________/  ")
    print(" "*15,"               |  ")
    print(" "*15,"               |  ")
    print(" "*15,"   ____________V_____________");
    print(" "*15,"  |                          |")
    print(" "*15,"  |    A <- 0  , Q_1 <- 0    |")
    print(" "*15,"  |                          |")
    print(" "*15,"  |    M <- Multiplicand     |")
    print(" "*15,"  |    Q <- Multiplier       |")
    print(" "*15,"  |                          |")
    print(" "*15,"  |    Count <- 4            |")
    print(" "*15,"  |__________________________| ")
    print(" "*15,"               |")
    print(" "*15,"               |")
    print(" "*15,"               |<-----------------")
    print(" "*15,"               |                  |")
    print(" "*15,"               V                  |")
    print(" "*15,"               ^                  |")
    print(" "*15,"              / \                 |")
    print(" "*15,"             /   \                |")
    print(" "*15,"            /     \               |")
    print(" "*15,"       10  /       \  01          |")
    print(" "*15,"      ____/ Q_0 Q_1 \____         |")
    print(" "*15,"     |    \         /    |        |")
    print(" "*15,"     |     \       /     |        |")
    print(" "*15,"     |      \     /      |        |")
    print(" "*15,"     |       \   /       |        |")
    print(" "*15,"     |        \ /        |        |")
    print(" "*15,"     |         V         |        |")
    print(" "*15," ____V____     |     ____V____    |")
    print(" "*15,"|         |    |    |         |   |")
    print(" "*15,"|  A=A-M  |    | 00 |  A=A+M  |   |")
    print(" "*15,"|_________|    | 11 |_________|   |")
    print(" "*15,"     |         |         |        |")
    print(" "*15,"     |___      |      ___|        |")
    print(" "*15,"         |     |     |            |")
    print(" "*15,"  _______V_____V_____V______      |")
    print(" "*15," |                          |     |")
    print(" "*15," |  Arithmetic Right Shift  |     |")
    print(" "*15," |                          |     |")
    print(" "*15," |          A Q Q_1         |     |")
    print(" "*15," |__________________________|     |")
    print(" "*15,"               |                  |")
    print(" "*15,"               |                  |")
    print(" "*15,"       ________V________          |")
    print(" "*15,"      |                 |         |")
    print(" "*15,"      |  Count=Count-1  |         |")
    print(" "*15,"      |_________________|         |")
    print(" "*15,"               |                  |")
    print(" "*15,"               |                  |")
    print(" "*15,"               V                  |")
    print(" "*15,"               ^                  |")
    print(" "*15,"              / \                 |")
    print(" "*15,"             /   \                |")
    print(" "*15,"            /     \               |")
    print(" "*15,"           /  Is   \      No      |")
    print(" "*15,"          / Count=0 \_____________|")
    print(" "*15,"          \    ?    /    ")
    print(" "*15,"           \       /     ")
    print(" "*15,"            \     /      ")
    print(" "*15,"             \   /       ")
    print(" "*15,"              \ /        ")
    print(" "*15,"               V         ")
    print(" "*15,"               |  ")
    print(" "*15,"               | Yes")
    print(" "*15,"           ____V____")
    print(" "*15,"          /         \ ")
    print(" "*15,"         |   Stop    |   ")
    print(" "*15,"          \_________/  ")

DrawImage()